### PR TITLE
Add log functionality

### PR DESCRIPTION
**Pull request by Huluti**
@philmmanjaro I think the functionality is ready. I let you take a look. It generates two files in a logs folder:

- mwr.log
- errors.log

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Will do when I find some time for it. Thx for adding it. Looks good.

**Comment by Huluti** [comment]
I've make a review: all the code is ready to enter in production.

**Comment by Huluti** [comment]
@philmmanjaro there is something strange: I can't view the logs files here:
-  http://repo.manjaro.org/logs/mwr.log
-  http://repo.manjaro.org/logs/errors.log

So, I'm not sure they exists. Can you take a look on the server?

**Comment by philmmanjaro** [comment]
It is easy. You broke the code, so nothing gets created at all. I hope I've fixed it now.

**Pull request merged**
